name: Label PRs via reusable workflow

on:
  pull_request_target:
    types: [synchronize, ready_for_review, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  call-reusable:
    uses: cockroachlabs/ai-pr-review-workflow/.github/workflows/test-simple-reusable-workflow.yml@main
    with:
      caller-repo: ${{ github.repository }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}